project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: ".."
base_url: "https://api.crowdin.com"

files: [
  {
    source: "src/RecentTopics.english.php",
    translation: "RecentTopics.%language%.php",
  }
]
